--Q1. What is the total revenue generated by male vs. female customers?

SELECT
    gender,
    SUM(purchase_amount) AS revenue
FROM customer_shopping
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT
    customer_id,
    purchase_amount
FROM customer_shopping
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer_shopping
  );
-- Q3. Which are the top 5 products with the highest average review rating?
 
SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating), 2) AS [Average Product Rating]
FROM customer_shopping
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS Average_Purchase_Amount
FROM customer_shopping
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS Average_Spend,
    SUM(purchase_amount) AS Total_Revenue
FROM customer_shopping
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5
    item_purchased,
    CAST(
        ROUND(
            100.0 * SUM(CASE
                            WHEN discount_applied = 'Yes' THEN 1
                            ELSE 0
                        END) / COUNT(*),
            2
        ) AS DECIMAL(5,2)
    ) AS Discount_Percentage
FROM customer_shopping
GROUP BY item_purchased
ORDER BY Discount_Percentage DESC;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count
FROM
(
    SELECT
        CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS Customer_Segment
    FROM customer_shopping
) AS Segments
GROUP BY Customer_Segment; 

-- Q8. What are the top 3 most purchased products within each category?

WITH ProductRank AS
(
    SELECT
        category,
        item_purchased,
        COUNT(*) AS Purchase_Count,
        ROW_NUMBER() OVER
        (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS Rank_No
    FROM customer_shopping
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    Purchase_Count
FROM ProductRank
WHERE Rank_No <= 3
ORDER BY category, Purchase_Count DESC; 

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    subscription_status,
    COUNT(*) AS Repeat_Buyers
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status; 

-- Q10. What is the revenue contribution of each age group?

SELECT
    age_group,
    SUM(purchase_amount) AS Total_Revenue,
    CAST(
        ROUND(
            100.0 * SUM(purchase_amount) /
            (SELECT SUM(purchase_amount) FROM customer_shopping),
            2
        ) AS DECIMAL(5,2)
    ) AS Revenue_Percentage
FROM customer_shopping
GROUP BY age_group
ORDER BY Total_Revenue DESC;
